apiVersion: v1
kind: Service
metadata:
  name: kpi-client
  labels:
    app: kpi-website
    app.kubernetes.io/name: kpi-website
spec:
  type: ClusterIP
  ports:
  - targetPort: 5742
    port: 3000
    name: client
  selector:
    app: kpi-website