services:
  postgres:
    container_name: kpi-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - kpi-data:/var/lib/postgresql/kpi
    build:
      dockerfile: Dockerfile
      context: ./database
  
  nginx:
    container_name: kpi-nginx
    depends_on:
      - server
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "5746:443"

  server:
    container_name: kpi-server
    environment:
      POSTGRES_HOST: postgres
    build:
      dockerfile: Dockerfile
      context: ./server
    depends_on:
      - postgres
    volumes:
      - /app/node_modules
      - ./server:/app

  client:
    container_name: kpi-client
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  adminer:
    container_name: kpi-adminer
    environment:
      ADMINER_PORT: "${ADMINER_PORT}"
      ADMINER_DEFAULT_SERVER: postgres
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - postgres

volumes:
  kpi-data:
    name: kpi-data