services:
  kpidb:
    container_name: kpidb
    image: postgres:latest
    restart: always
    environment:
      <<:
        POSTGRES_USER: "${DB_USERNAME}"
        POSTGRES_PASSWORD: "${DB_PASSWORD}"
        POSTGRES_DB: "${DB_NAME}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - kpi-data:/var/lib/postgresql/data
      - "./scripts/init.sql:/docker-entrypoint-initdb.d/scripts/init.sql"
    ports:
      - "${DB_PORT}:${DB_PORT}"
  
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - kpidb
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      <<:
        POSTGRES_HOST: kpidb

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - kpidb
    environment:
      ADMINER_DEFAULT_SERVER: kpidb

volumes:
  kpi-data:
    name: kpi-data
