apiVersion: v1
kind: Service
metadata:
  name: kpi-backend
  labels:
    app: kpi-website
    app.kubernetes.io/name: kpi-website
spec:
  type: ClusterIP
  ports:
  - targetPort: 6633
    port: 6633
    name: node
  selector:
    app: kpi-website