# Client service for readonly db connections
apiVersion: v1
kind: Service
metadata:
  name: kpi-db-readonly
  labels:
    app: kpi-website
    app.kubernetes.io/name: kpi-website
    readonly: "true"
spec:
  type: ClusterIP
  ports:
  - targetPort: 5432
    port: 7476
    name: database-readonly
  selector:
    app: kpi-website