apiVersion: v1
kind: Service
metadata:
  name: kpi-db
  labels:
    app: kpi-website
    app.kubernetes.io/name: kpi-website
spec:
  type: ClusterIP
  ports:
  - targetPort: 5743
    port: 5432
    name: database
  selector:
    app: kpi-website