apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kpi-db
spec:
  serviceName: kpi-db-service
  selector:
    matchLabels:
      app: kpi-website
      app.kubernetes.io/name: kpi-website
  replicas: 2
  template:
    metadata:
      labels:
        app: kpi-website
        app.kubernetes.io/name: kpi-website
    spec:
      containers:
      - name: kpi-db
        image: postgres:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7475
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
            storage: "16Gi"
          limits:
            memory: "1Gi"
            cpu: "1000m"
            storage: "32Gi"
        volumeMounts:
        - name: kpi-db-disk
          mountPath: /var/lib/postgres/kpi
        envFrom:
        - configMapRef:
        name: kpi-db-config