apiVersion: v1
kind: Service
metadata:
  name: kpi-server
  labels:
    app: kpi-website
    app.kubernetes.io/name: kpi-website
spec:
  type: ClusterIP
  ports:
  - targetPort: 5746
    port: 3050
    name: nginx
  selector:
    app: kpi-website